import { NextRequest, NextResponse } from "next/server";
import { auth } from "@/lib/auth";
import { prisma } from "@/lib/prisma";

interface BacklinkEntry {
  domain: string;
  url: string;
  anchor: string;
  spamScore: number;
  domainRank: number;
  dofollow: boolean;
  firstSeen: string | null;
  toxic: boolean;
}

// GET /api/projects/disavow?projectId=xxx
// Returns a plain-text disavow file for Google Search Console
export async function GET(req: NextRequest) {
  const session = await auth();
  if (!session?.user) {
    return new NextResponse("Unauthorized", { status: 401 });
  }

  const userId = (session.user as { id: string }).id;
  const projectId = req.nextUrl.searchParams.get("projectId");

  if (!projectId) {
    return new NextResponse("projectId is required", { status: 400 });
  }

  const project = await prisma.project.findFirst({
    where: {
      id: projectId,
      tenant: { members: { some: { userId } } },
    },
    include: {
      reportSnapshots: {
        where: { toxicLinksJson: { not: null } },
        orderBy: { createdAt: "desc" },
        take: 1,
        select: { toxicLinksJson: true, createdAt: true, domainRank: true },
      },
    },
  });

  if (!project) {
    return new NextResponse("Project not found", { status: 404 });
  }

  const snapshot = project.reportSnapshots[0];
  if (!snapshot?.toxicLinksJson) {
    return new NextResponse("No toxic link data found. Run a report first.", { status: 404 });
  }

  let toxicLinks: BacklinkEntry[] = [];
  try {
    toxicLinks = JSON.parse(snapshot.toxicLinksJson);
  } catch {
    return new NextResponse("Could not parse toxic link data", { status: 500 });
  }

  // Collect unique domains to disavow
  const domains = [...new Set(toxicLinks.map((l) => l.domain))].sort();

  const lines: string[] = [
    `# Disavow File for ${project.domain}`,
    `# Generated by SearchAuditPro on ${new Date().toISOString().split("T")[0]}`,
    `# Report date: ${snapshot.createdAt.toISOString().split("T")[0]}`,
    `# Total toxic domains: ${domains.length}`,
    `# Total toxic links: ${toxicLinks.length}`,
    `#`,
    `# HOW TO USE:`,
    `# 1. Go to Google Search Console → Disavow links tool`,
    `# 2. Select your property (${project.domain})`,
    `# 3. Upload this file`,
    `# 4. Google will stop counting these links in your ranking calculations`,
    `#`,
    `# WHAT IS A TOXIC LINK?`,
    `# Links with a spam score above 60 (on DataForSEO's 0-100 scale) are`,
    `# considered toxic. These come from low-quality, spammy, or link-farm`,
    `# sites that can hurt your search rankings.`,
    `#`,
    ``,
    ...domains.map((d) => `domain:${d}`),
  ];

  return new NextResponse(lines.join("\n"), {
    status: 200,
    headers: {
      "Content-Type": "text/plain; charset=utf-8",
      "Content-Disposition": `attachment; filename="disavow-${project.domain}-${new Date().toISOString().split("T")[0]}.txt"`,
    },
  });
}
